# Generated by Django 5.1 on 2024-08-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=180, verbose_name='Prénoms')),
                ('adresse', models.TextField()),
                ('pays', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('note', models.FloatField(help_text='Donnez une note entre 0 et 5')),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_produit_ids', to='boutique.produit')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_client_ids', to='customer.client')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('date_commande', models.DateTimeField()),
                ('active_paiement', models.BooleanField(default=False)),
                ('active_livraison', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commande_clients_ids', to='customer.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('date_livraison', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('commande_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison_commande_id', to='customer.commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier_clients_ids', to='customer.client')),
                ('produit_ids', models.ManyToManyField(related_name='panier_produit_ids', to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='panier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commande_panier_ids', to='customer.panier'),
        ),
    ]
