# Generated by Django 5.1 on 2024-08-29 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodeDePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
            ],
            options={
                'verbose_name': 'Moyen de Paiement',
                'verbose_name_plural': 'Moyens de Paiement',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('date_paiement', models.DateTimeField()),
                ('status_paiement', models.BooleanField()),
                ('commande_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiement_commande_id', to='customer.commande')),
                ('moyen_de_paiement_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_ids', to='paiement.methodedepaiement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
